SELECT CONCAT("SQL ", "Tutorial ", "is ", "fun!") AS ConcatenatedString; 
SELECT LTRIM("     SQL Tutorial") AS LeftTrimmedString;
SELECT RTRIM("SQL Tutorial     ") AS RightTrimmedString;
SELECT TRIM('    SQL Tutorial    ') AS TrimmedString;
SELECT LCASE("SQL Tutorial is FUN!");
SELECT LOWER("SQL Tutorial is FUN!");
SELECT UCASE("SQL Tutorial is FUN!");
SELECT UPPER("SQL Tutorial is FUN!");,
SELECT SUBSTRING("SQL Tutorial", 5, 3) AS ExtractString;
SELECT LENGTH("SQL Tutorial") AS LengthOfString;
SELECT LTRIM('    OLÁ')
SELECT LTRIM('    OLÁ') AS RESULTADO;
SELECT RTRIM('OLÁ     ') AS RESULTADO;
SELECT TRIM('    OLÁ    ') AS RESULTADO;
SELECT CONCAT('OLÁ', ' ', 'TUDO BEM','?') AS RESULTADO;
SELECT UPPER('olá, tudo bem?') AS RESULTADO;
SELECT LOWER('OLÁ, TUDO BEM?') AS RESULTADO;
SELECT SUBSTRING('OLÁ, TUDO BEM?', 6) AS RESULTADO;
SELECT SUBSTRING('OLÁ, TUDO BEM?', 6, 4) AS RESULTADO;
SELECT CONCAT(NOME, ' (', CPF, ') ') AS RESULTADO FROM TABELA_DE_CLIENTES;

SELECT DISTINCT DATA_VENDA FROM NOTAS_FISCAIS;

SELECT DISTINCT DATA_VENDA,
DAYNAME(DATA_VENDA) AS DIA, MONTHNAME(DATA_VENDA) AS MES, YEAR(DATA_VENDA) AS ANO FROM NOTAS_FISCAIS;

SELECT (23+((25-2)/2)*45) AS RESULTADO;
SELECT CEILING(12.33333232323) AS RESULTADO;
SELECT ROUND(12.33333232323) AS RESULTADO;
SELECT ROUND(12.7777232323) AS RESULTADO;
SELECT FLOOR(12.7777232323) AS RESULTADO;
SELECT RAND() AS RESULTADO;

SELECT NUMERO, QUANTIDADE, PRECO
FROM ITENS_NOTAS_FISCAIS;

SELECT NUMERO, QUANTIDADE, PRECO, QUANTIDADE * PRECO AS FATURAMENTO
FROM ITENS_NOTAS_FISCAIS;

SELECT NUMERO, QUANTIDADE, PRECO, ROUND(QUANTIDADE * PRECO, 2) AS FATURAMENTO
FROM ITENS_NOTAS_FISCAIS;

SELECT CURRENT_TIMESTAMP() AS RESULTADO;
SELECT CONCAT('O dia de hoje é: ', CURRENT_TIMESTAMP()) AS RESULTADO;

SELECT CONCAT('O dia de hoje é: ', 
DATE_FORMAT(CURRENT_TIMESTAMP(),'%Y') ) AS RESULTADO;

SELECT CONCAT('O dia de hoje é: ', 
DATE_FORMAT(CURRENT_TIMESTAMP(),'%y') ) AS RESULTADO;

SELECT CONCAT('O dia de hoje é: ', 
DATE_FORMAT(CURRENT_TIMESTAMP(),'%m/%y') ) AS RESULTADO;

SELECT CONCAT('O dia de hoje é: ', 
DATE_FORMAT(CURRENT_TIMESTAMP(),'%d/%m/%Y') ) AS RESULTADO;

SELECT CONCAT('O dia de hoje é: ', 
DATE_FORMAT(CURRENT_TIMESTAMP(),'%W, %d/%m/%Y') ) AS RESULTADO;

SELECT CONCAT('O dia de hoje é: ', 
DATE_FORMAT(CURRENT_TIMESTAMP(),'%d/%m/%Y - %U') ) AS RESULTADO;

SELECT CONVERT(23.3, CHAR) AS RESULTADO;
SELECT SUBSTRING(CONVERT(23.3, CHAR),1,1) AS RESULTADO;